apiVersion: v1
kind: ServiceAccount
metadata:
  name: sienna-integration-user
  # namespace will be specified during kubectl apply
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sienna-admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sienna-admin-binding
subjects:
- kind: ServiceAccount
  name: sienna-integration-user
  # namespace will be specified during kubectl apply
roleRef:
  kind: ClusterRole
  name: sienna-admin-role
  apiGroup: rbac.authorization.k8s.io 
